
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T> = DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>> & T

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }> & T

interface _GlobalComponents {
  'TicketTable': typeof import("../../app/components/TicketTable.vue")['default']
  'B24Accordion': typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Accordion.vue")['default']
  'B24Advice': typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Advice.vue")['default']
  'B24Alert': typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Alert.vue")['default']
  'B24App': typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/App.vue")['default']
  'B24Avatar': typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Avatar.vue")['default']
  'B24AvatarGroup': typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/AvatarGroup.vue")['default']
  'B24Badge': typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Badge.vue")['default']
  'B24Button': typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Button.vue")['default']
  'B24ButtonGroup': typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/ButtonGroup.vue")['default']
  'B24Calendar': typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Calendar.vue")['default']
  'B24Checkbox': typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Checkbox.vue")['default']
  'B24Chip': typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Chip.vue")['default']
  'B24Collapsible': typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Collapsible.vue")['default']
  'B24Container': typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Container.vue")['default']
  'B24Countdown': typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Countdown.vue")['default']
  'B24DescriptionList': typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/DescriptionList.vue")['default']
  'B24DropdownMenu': typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/DropdownMenu.vue")['default']
  'B24DropdownMenuContent': typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/DropdownMenuContent.vue")['default']
  'B24Form': typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Form.vue")['default']
  'B24FormField': typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/FormField.vue")['default']
  'B24Input': typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Input.vue")['default']
  'B24InputMenu': typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/InputMenu.vue")['default']
  'B24InputNumber': typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/InputNumber.vue")['default']
  'B24Kbd': typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Kbd.vue")['default']
  'B24Link': typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Link.vue")['default']
  'B24LinkBase': typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/LinkBase.vue")['default']
  'B24Modal': typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Modal.vue")['default']
  'B24ModalDialogClose': typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/ModalDialogClose.vue")['default']
  'B24Navbar': typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Navbar.vue")['default']
  'B24NavbarDivider': typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/NavbarDivider.vue")['default']
  'B24NavbarSection': typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/NavbarSection.vue")['default']
  'B24NavbarSpacer': typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/NavbarSpacer.vue")['default']
  'B24NavigationMenu': typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/NavigationMenu.vue")['default']
  'B24OverlayProvider': typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/OverlayProvider.vue")['default']
  'B24Popover': typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Popover.vue")['default']
  'B24Progress': typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Progress.vue")['default']
  'B24RadioGroup': typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/RadioGroup.vue")['default']
  'B24Range': typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Range.vue")['default']
  'B24Select': typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Select.vue")['default']
  'B24SelectMenu': typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/SelectMenu.vue")['default']
  'B24Separator': typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Separator.vue")['default']
  'B24Sidebar': typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Sidebar.vue")['default']
  'B24SidebarBody': typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/SidebarBody.vue")['default']
  'B24SidebarFooter': typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/SidebarFooter.vue")['default']
  'B24SidebarHeader': typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/SidebarHeader.vue")['default']
  'B24SidebarHeading': typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/SidebarHeading.vue")['default']
  'B24SidebarLayout': typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/SidebarLayout.vue")['default']
  'B24SidebarSection': typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/SidebarSection.vue")['default']
  'B24SidebarSpacer': typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/SidebarSpacer.vue")['default']
  'B24Skeleton': typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Skeleton.vue")['default']
  'B24Slideover': typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Slideover.vue")['default']
  'B24Switch': typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Switch.vue")['default']
  'B24Tabs': typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Tabs.vue")['default']
  'B24Textarea': typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Textarea.vue")['default']
  'B24Toast': typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Toast.vue")['default']
  'B24Toaster': typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Toaster.vue")['default']
  'B24Tooltip': typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Tooltip.vue")['default']
  'B24TableWrapper': typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/content/TableWrapper.vue")['default']
  'ProseA': typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/prose/A.vue")['default']
  'ProseBlockquote': typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/prose/Blockquote.vue")['default']
  'ProseCode': typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/prose/Code.vue")['default']
  'ProseEm': typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/prose/Em.vue")['default']
  'ProseH1': typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/prose/H1.vue")['default']
  'ProseH2': typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/prose/H2.vue")['default']
  'ProseH3': typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/prose/H3.vue")['default']
  'ProseH4': typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/prose/H4.vue")['default']
  'ProseH5': typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/prose/H5.vue")['default']
  'ProseH6': typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/prose/H6.vue")['default']
  'ProseHr': typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/prose/Hr.vue")['default']
  'ProseImg': typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/prose/Img.vue")['default']
  'ProseLi': typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/prose/Li.vue")['default']
  'ProseOl': typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/prose/Ol.vue")['default']
  'ProseP': typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/prose/P.vue")['default']
  'ProsePre': typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/prose/Pre.vue")['default']
  'ProseStrong': typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/prose/Strong.vue")['default']
  'ProseTable': typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/prose/Table.vue")['default']
  'ProseTbody': typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/prose/Tbody.vue")['default']
  'ProseTd': typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/prose/Td.vue")['default']
  'ProseTh': typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/prose/Th.vue")['default']
  'ProseThead': typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/prose/Thead.vue")['default']
  'ProseTr': typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/prose/Tr.vue")['default']
  'ProseUl': typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/prose/Ul.vue")['default']
  'NuxtWelcome': typeof import("../../node_modules/nuxt/dist/app/components/welcome.vue")['default']
  'NuxtLayout': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
  'NuxtErrorBoundary': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']
  'ClientOnly': typeof import("../../node_modules/nuxt/dist/app/components/client-only")['default']
  'DevOnly': typeof import("../../node_modules/nuxt/dist/app/components/dev-only")['default']
  'ServerPlaceholder': typeof import("../../node_modules/nuxt/dist/app/components/server-placeholder")['default']
  'NuxtLink': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-link")['default']
  'NuxtLoadingIndicator': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
  'NuxtTime': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']
  'NuxtRouteAnnouncer': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
  'NuxtImg': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
  'NuxtPicture': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
  'ColorScheme': typeof import("../../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
  'NuxtPage': typeof import("../../node_modules/nuxt/dist/pages/runtime/page-placeholder")['default']
  'NoScript': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['NoScript']
  'Link': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Link']
  'Base': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Base']
  'Title': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Title']
  'Meta': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Meta']
  'Style': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Style']
  'Head': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Head']
  'Html': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Html']
  'Body': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Body']
  'NuxtIsland': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-island")['default']
  'LazyTicketTable': LazyComponent<typeof import("../../app/components/TicketTable.vue")['default']>
  'LazyB24Accordion': LazyComponent<typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Accordion.vue")['default']>
  'LazyB24Advice': LazyComponent<typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Advice.vue")['default']>
  'LazyB24Alert': LazyComponent<typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Alert.vue")['default']>
  'LazyB24App': LazyComponent<typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/App.vue")['default']>
  'LazyB24Avatar': LazyComponent<typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Avatar.vue")['default']>
  'LazyB24AvatarGroup': LazyComponent<typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/AvatarGroup.vue")['default']>
  'LazyB24Badge': LazyComponent<typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Badge.vue")['default']>
  'LazyB24Button': LazyComponent<typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Button.vue")['default']>
  'LazyB24ButtonGroup': LazyComponent<typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/ButtonGroup.vue")['default']>
  'LazyB24Calendar': LazyComponent<typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Calendar.vue")['default']>
  'LazyB24Checkbox': LazyComponent<typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Checkbox.vue")['default']>
  'LazyB24Chip': LazyComponent<typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Chip.vue")['default']>
  'LazyB24Collapsible': LazyComponent<typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Collapsible.vue")['default']>
  'LazyB24Container': LazyComponent<typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Container.vue")['default']>
  'LazyB24Countdown': LazyComponent<typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Countdown.vue")['default']>
  'LazyB24DescriptionList': LazyComponent<typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/DescriptionList.vue")['default']>
  'LazyB24DropdownMenu': LazyComponent<typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/DropdownMenu.vue")['default']>
  'LazyB24DropdownMenuContent': LazyComponent<typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/DropdownMenuContent.vue")['default']>
  'LazyB24Form': LazyComponent<typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Form.vue")['default']>
  'LazyB24FormField': LazyComponent<typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/FormField.vue")['default']>
  'LazyB24Input': LazyComponent<typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Input.vue")['default']>
  'LazyB24InputMenu': LazyComponent<typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/InputMenu.vue")['default']>
  'LazyB24InputNumber': LazyComponent<typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/InputNumber.vue")['default']>
  'LazyB24Kbd': LazyComponent<typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Kbd.vue")['default']>
  'LazyB24Link': LazyComponent<typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Link.vue")['default']>
  'LazyB24LinkBase': LazyComponent<typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/LinkBase.vue")['default']>
  'LazyB24Modal': LazyComponent<typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Modal.vue")['default']>
  'LazyB24ModalDialogClose': LazyComponent<typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/ModalDialogClose.vue")['default']>
  'LazyB24Navbar': LazyComponent<typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Navbar.vue")['default']>
  'LazyB24NavbarDivider': LazyComponent<typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/NavbarDivider.vue")['default']>
  'LazyB24NavbarSection': LazyComponent<typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/NavbarSection.vue")['default']>
  'LazyB24NavbarSpacer': LazyComponent<typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/NavbarSpacer.vue")['default']>
  'LazyB24NavigationMenu': LazyComponent<typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/NavigationMenu.vue")['default']>
  'LazyB24OverlayProvider': LazyComponent<typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/OverlayProvider.vue")['default']>
  'LazyB24Popover': LazyComponent<typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Popover.vue")['default']>
  'LazyB24Progress': LazyComponent<typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Progress.vue")['default']>
  'LazyB24RadioGroup': LazyComponent<typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/RadioGroup.vue")['default']>
  'LazyB24Range': LazyComponent<typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Range.vue")['default']>
  'LazyB24Select': LazyComponent<typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Select.vue")['default']>
  'LazyB24SelectMenu': LazyComponent<typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/SelectMenu.vue")['default']>
  'LazyB24Separator': LazyComponent<typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Separator.vue")['default']>
  'LazyB24Sidebar': LazyComponent<typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Sidebar.vue")['default']>
  'LazyB24SidebarBody': LazyComponent<typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/SidebarBody.vue")['default']>
  'LazyB24SidebarFooter': LazyComponent<typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/SidebarFooter.vue")['default']>
  'LazyB24SidebarHeader': LazyComponent<typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/SidebarHeader.vue")['default']>
  'LazyB24SidebarHeading': LazyComponent<typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/SidebarHeading.vue")['default']>
  'LazyB24SidebarLayout': LazyComponent<typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/SidebarLayout.vue")['default']>
  'LazyB24SidebarSection': LazyComponent<typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/SidebarSection.vue")['default']>
  'LazyB24SidebarSpacer': LazyComponent<typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/SidebarSpacer.vue")['default']>
  'LazyB24Skeleton': LazyComponent<typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Skeleton.vue")['default']>
  'LazyB24Slideover': LazyComponent<typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Slideover.vue")['default']>
  'LazyB24Switch': LazyComponent<typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Switch.vue")['default']>
  'LazyB24Tabs': LazyComponent<typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Tabs.vue")['default']>
  'LazyB24Textarea': LazyComponent<typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Textarea.vue")['default']>
  'LazyB24Toast': LazyComponent<typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Toast.vue")['default']>
  'LazyB24Toaster': LazyComponent<typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Toaster.vue")['default']>
  'LazyB24Tooltip': LazyComponent<typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Tooltip.vue")['default']>
  'LazyB24TableWrapper': LazyComponent<typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/content/TableWrapper.vue")['default']>
  'LazyProseA': LazyComponent<typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/prose/A.vue")['default']>
  'LazyProseBlockquote': LazyComponent<typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/prose/Blockquote.vue")['default']>
  'LazyProseCode': LazyComponent<typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/prose/Code.vue")['default']>
  'LazyProseEm': LazyComponent<typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/prose/Em.vue")['default']>
  'LazyProseH1': LazyComponent<typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/prose/H1.vue")['default']>
  'LazyProseH2': LazyComponent<typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/prose/H2.vue")['default']>
  'LazyProseH3': LazyComponent<typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/prose/H3.vue")['default']>
  'LazyProseH4': LazyComponent<typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/prose/H4.vue")['default']>
  'LazyProseH5': LazyComponent<typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/prose/H5.vue")['default']>
  'LazyProseH6': LazyComponent<typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/prose/H6.vue")['default']>
  'LazyProseHr': LazyComponent<typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/prose/Hr.vue")['default']>
  'LazyProseImg': LazyComponent<typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/prose/Img.vue")['default']>
  'LazyProseLi': LazyComponent<typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/prose/Li.vue")['default']>
  'LazyProseOl': LazyComponent<typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/prose/Ol.vue")['default']>
  'LazyProseP': LazyComponent<typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/prose/P.vue")['default']>
  'LazyProsePre': LazyComponent<typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/prose/Pre.vue")['default']>
  'LazyProseStrong': LazyComponent<typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/prose/Strong.vue")['default']>
  'LazyProseTable': LazyComponent<typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/prose/Table.vue")['default']>
  'LazyProseTbody': LazyComponent<typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/prose/Tbody.vue")['default']>
  'LazyProseTd': LazyComponent<typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/prose/Td.vue")['default']>
  'LazyProseTh': LazyComponent<typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/prose/Th.vue")['default']>
  'LazyProseThead': LazyComponent<typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/prose/Thead.vue")['default']>
  'LazyProseTr': LazyComponent<typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/prose/Tr.vue")['default']>
  'LazyProseUl': LazyComponent<typeof import("../../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/prose/Ul.vue")['default']>
  'LazyNuxtWelcome': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/welcome.vue")['default']>
  'LazyNuxtLayout': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-layout")['default']>
  'LazyNuxtErrorBoundary': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']>
  'LazyClientOnly': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/client-only")['default']>
  'LazyDevOnly': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/dev-only")['default']>
  'LazyServerPlaceholder': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
  'LazyNuxtLink': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-link")['default']>
  'LazyNuxtLoadingIndicator': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']>
  'LazyNuxtTime': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']>
  'LazyNuxtRouteAnnouncer': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']>
  'LazyNuxtImg': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']>
  'LazyNuxtPicture': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']>
  'LazyColorScheme': LazyComponent<typeof import("../../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']>
  'LazyNuxtPage': LazyComponent<typeof import("../../node_modules/nuxt/dist/pages/runtime/page-placeholder")['default']>
  'LazyNoScript': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['NoScript']>
  'LazyLink': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Link']>
  'LazyBase': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Base']>
  'LazyTitle': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Title']>
  'LazyMeta': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Meta']>
  'LazyStyle': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Style']>
  'LazyHead': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Head']>
  'LazyHtml': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Html']>
  'LazyBody': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Body']>
  'LazyNuxtIsland': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-island")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export {}
