
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T> = DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>> & T

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }> & T


export const TicketTable: typeof import("../app/components/TicketTable.vue")['default']
export const B24Accordion: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Accordion.vue")['default']
export const B24Advice: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Advice.vue")['default']
export const B24Alert: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Alert.vue")['default']
export const B24App: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/App.vue")['default']
export const B24Avatar: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Avatar.vue")['default']
export const B24AvatarGroup: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/AvatarGroup.vue")['default']
export const B24Badge: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Badge.vue")['default']
export const B24Button: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Button.vue")['default']
export const B24ButtonGroup: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/ButtonGroup.vue")['default']
export const B24Calendar: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Calendar.vue")['default']
export const B24Checkbox: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Checkbox.vue")['default']
export const B24Chip: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Chip.vue")['default']
export const B24Collapsible: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Collapsible.vue")['default']
export const B24Container: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Container.vue")['default']
export const B24Countdown: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Countdown.vue")['default']
export const B24DescriptionList: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/DescriptionList.vue")['default']
export const B24DropdownMenu: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/DropdownMenu.vue")['default']
export const B24DropdownMenuContent: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/DropdownMenuContent.vue")['default']
export const B24Form: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Form.vue")['default']
export const B24FormField: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/FormField.vue")['default']
export const B24Input: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Input.vue")['default']
export const B24InputMenu: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/InputMenu.vue")['default']
export const B24InputNumber: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/InputNumber.vue")['default']
export const B24Kbd: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Kbd.vue")['default']
export const B24Link: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Link.vue")['default']
export const B24LinkBase: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/LinkBase.vue")['default']
export const B24Modal: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Modal.vue")['default']
export const B24ModalDialogClose: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/ModalDialogClose.vue")['default']
export const B24Navbar: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Navbar.vue")['default']
export const B24NavbarDivider: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/NavbarDivider.vue")['default']
export const B24NavbarSection: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/NavbarSection.vue")['default']
export const B24NavbarSpacer: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/NavbarSpacer.vue")['default']
export const B24NavigationMenu: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/NavigationMenu.vue")['default']
export const B24OverlayProvider: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/OverlayProvider.vue")['default']
export const B24Popover: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Popover.vue")['default']
export const B24Progress: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Progress.vue")['default']
export const B24RadioGroup: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/RadioGroup.vue")['default']
export const B24Range: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Range.vue")['default']
export const B24Select: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Select.vue")['default']
export const B24SelectMenu: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/SelectMenu.vue")['default']
export const B24Separator: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Separator.vue")['default']
export const B24Sidebar: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Sidebar.vue")['default']
export const B24SidebarBody: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/SidebarBody.vue")['default']
export const B24SidebarFooter: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/SidebarFooter.vue")['default']
export const B24SidebarHeader: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/SidebarHeader.vue")['default']
export const B24SidebarHeading: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/SidebarHeading.vue")['default']
export const B24SidebarLayout: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/SidebarLayout.vue")['default']
export const B24SidebarSection: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/SidebarSection.vue")['default']
export const B24SidebarSpacer: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/SidebarSpacer.vue")['default']
export const B24Skeleton: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Skeleton.vue")['default']
export const B24Slideover: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Slideover.vue")['default']
export const B24Switch: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Switch.vue")['default']
export const B24Tabs: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Tabs.vue")['default']
export const B24Textarea: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Textarea.vue")['default']
export const B24Toast: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Toast.vue")['default']
export const B24Toaster: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Toaster.vue")['default']
export const B24Tooltip: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Tooltip.vue")['default']
export const B24TableWrapper: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/content/TableWrapper.vue")['default']
export const ProseA: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/prose/A.vue")['default']
export const ProseBlockquote: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/prose/Blockquote.vue")['default']
export const ProseCode: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/prose/Code.vue")['default']
export const ProseEm: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/prose/Em.vue")['default']
export const ProseH1: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/prose/H1.vue")['default']
export const ProseH2: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/prose/H2.vue")['default']
export const ProseH3: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/prose/H3.vue")['default']
export const ProseH4: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/prose/H4.vue")['default']
export const ProseH5: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/prose/H5.vue")['default']
export const ProseH6: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/prose/H6.vue")['default']
export const ProseHr: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/prose/Hr.vue")['default']
export const ProseImg: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/prose/Img.vue")['default']
export const ProseLi: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/prose/Li.vue")['default']
export const ProseOl: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/prose/Ol.vue")['default']
export const ProseP: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/prose/P.vue")['default']
export const ProsePre: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/prose/Pre.vue")['default']
export const ProseStrong: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/prose/Strong.vue")['default']
export const ProseTable: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/prose/Table.vue")['default']
export const ProseTbody: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/prose/Tbody.vue")['default']
export const ProseTd: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/prose/Td.vue")['default']
export const ProseTh: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/prose/Th.vue")['default']
export const ProseThead: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/prose/Thead.vue")['default']
export const ProseTr: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/prose/Tr.vue")['default']
export const ProseUl: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/prose/Ul.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtTime: typeof import("../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const ColorScheme: typeof import("../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyTicketTable: LazyComponent<typeof import("../app/components/TicketTable.vue")['default']>
export const LazyB24Accordion: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Accordion.vue")['default']>
export const LazyB24Advice: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Advice.vue")['default']>
export const LazyB24Alert: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Alert.vue")['default']>
export const LazyB24App: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/App.vue")['default']>
export const LazyB24Avatar: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Avatar.vue")['default']>
export const LazyB24AvatarGroup: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/AvatarGroup.vue")['default']>
export const LazyB24Badge: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Badge.vue")['default']>
export const LazyB24Button: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Button.vue")['default']>
export const LazyB24ButtonGroup: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/ButtonGroup.vue")['default']>
export const LazyB24Calendar: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Calendar.vue")['default']>
export const LazyB24Checkbox: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Checkbox.vue")['default']>
export const LazyB24Chip: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Chip.vue")['default']>
export const LazyB24Collapsible: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Collapsible.vue")['default']>
export const LazyB24Container: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Container.vue")['default']>
export const LazyB24Countdown: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Countdown.vue")['default']>
export const LazyB24DescriptionList: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/DescriptionList.vue")['default']>
export const LazyB24DropdownMenu: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/DropdownMenu.vue")['default']>
export const LazyB24DropdownMenuContent: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/DropdownMenuContent.vue")['default']>
export const LazyB24Form: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Form.vue")['default']>
export const LazyB24FormField: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/FormField.vue")['default']>
export const LazyB24Input: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Input.vue")['default']>
export const LazyB24InputMenu: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/InputMenu.vue")['default']>
export const LazyB24InputNumber: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/InputNumber.vue")['default']>
export const LazyB24Kbd: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Kbd.vue")['default']>
export const LazyB24Link: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Link.vue")['default']>
export const LazyB24LinkBase: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/LinkBase.vue")['default']>
export const LazyB24Modal: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Modal.vue")['default']>
export const LazyB24ModalDialogClose: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/ModalDialogClose.vue")['default']>
export const LazyB24Navbar: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Navbar.vue")['default']>
export const LazyB24NavbarDivider: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/NavbarDivider.vue")['default']>
export const LazyB24NavbarSection: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/NavbarSection.vue")['default']>
export const LazyB24NavbarSpacer: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/NavbarSpacer.vue")['default']>
export const LazyB24NavigationMenu: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/NavigationMenu.vue")['default']>
export const LazyB24OverlayProvider: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/OverlayProvider.vue")['default']>
export const LazyB24Popover: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Popover.vue")['default']>
export const LazyB24Progress: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Progress.vue")['default']>
export const LazyB24RadioGroup: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/RadioGroup.vue")['default']>
export const LazyB24Range: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Range.vue")['default']>
export const LazyB24Select: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Select.vue")['default']>
export const LazyB24SelectMenu: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/SelectMenu.vue")['default']>
export const LazyB24Separator: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Separator.vue")['default']>
export const LazyB24Sidebar: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Sidebar.vue")['default']>
export const LazyB24SidebarBody: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/SidebarBody.vue")['default']>
export const LazyB24SidebarFooter: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/SidebarFooter.vue")['default']>
export const LazyB24SidebarHeader: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/SidebarHeader.vue")['default']>
export const LazyB24SidebarHeading: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/SidebarHeading.vue")['default']>
export const LazyB24SidebarLayout: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/SidebarLayout.vue")['default']>
export const LazyB24SidebarSection: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/SidebarSection.vue")['default']>
export const LazyB24SidebarSpacer: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/SidebarSpacer.vue")['default']>
export const LazyB24Skeleton: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Skeleton.vue")['default']>
export const LazyB24Slideover: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Slideover.vue")['default']>
export const LazyB24Switch: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Switch.vue")['default']>
export const LazyB24Tabs: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Tabs.vue")['default']>
export const LazyB24Textarea: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Textarea.vue")['default']>
export const LazyB24Toast: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Toast.vue")['default']>
export const LazyB24Toaster: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Toaster.vue")['default']>
export const LazyB24Tooltip: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Tooltip.vue")['default']>
export const LazyB24TableWrapper: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/content/TableWrapper.vue")['default']>
export const LazyProseA: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/prose/A.vue")['default']>
export const LazyProseBlockquote: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/prose/Blockquote.vue")['default']>
export const LazyProseCode: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/prose/Code.vue")['default']>
export const LazyProseEm: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/prose/Em.vue")['default']>
export const LazyProseH1: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/prose/H1.vue")['default']>
export const LazyProseH2: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/prose/H2.vue")['default']>
export const LazyProseH3: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/prose/H3.vue")['default']>
export const LazyProseH4: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/prose/H4.vue")['default']>
export const LazyProseH5: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/prose/H5.vue")['default']>
export const LazyProseH6: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/prose/H6.vue")['default']>
export const LazyProseHr: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/prose/Hr.vue")['default']>
export const LazyProseImg: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/prose/Img.vue")['default']>
export const LazyProseLi: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/prose/Li.vue")['default']>
export const LazyProseOl: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/prose/Ol.vue")['default']>
export const LazyProseP: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/prose/P.vue")['default']>
export const LazyProsePre: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/prose/Pre.vue")['default']>
export const LazyProseStrong: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/prose/Strong.vue")['default']>
export const LazyProseTable: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/prose/Table.vue")['default']>
export const LazyProseTbody: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/prose/Tbody.vue")['default']>
export const LazyProseTd: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/prose/Td.vue")['default']>
export const LazyProseTh: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/prose/Th.vue")['default']>
export const LazyProseThead: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/prose/Thead.vue")['default']>
export const LazyProseTr: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/prose/Tr.vue")['default']>
export const LazyProseUl: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/prose/Ul.vue")['default']>
export const LazyNuxtWelcome: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']>
export const LazyNuxtLayout: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']>
export const LazyNuxtErrorBoundary: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']>
export const LazyClientOnly: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']>
export const LazyDevOnly: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']>
export const LazyServerPlaceholder: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyNuxtLink: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']>
export const LazyNuxtLoadingIndicator: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']>
export const LazyNuxtTime: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']>
export const LazyNuxtRouteAnnouncer: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']>
export const LazyNuxtImg: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']>
export const LazyNuxtPicture: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']>
export const LazyColorScheme: LazyComponent<typeof import("../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']>
export const LazyNuxtPage: LazyComponent<typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']>
export const LazyNoScript: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']>
export const LazyLink: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']>
export const LazyBase: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']>
export const LazyTitle: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']>
export const LazyMeta: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']>
export const LazyStyle: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']>
export const LazyHead: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']>
export const LazyHtml: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']>
export const LazyBody: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']>
export const LazyNuxtIsland: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']>

export const componentNames: string[]
