
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T> = DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>> & T

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }> & T


export const CompanyList: typeof import("../app/components/CompanyList.vue")['default']
export const TicketTable: typeof import("../app/components/TicketTable.vue")['default']
export const ProseADVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/A.d.vue")['default']
export const ProseA: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/A.vue")['default']
export const ProseAccordionDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Accordion.d.vue")['default']
export const ProseAccordion: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Accordion.vue")['default']
export const ProseAccordionItemDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/AccordionItem.d.vue")['default']
export const ProseAccordionItem: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/AccordionItem.vue")['default']
export const ProseBadgeDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Badge.d.vue")['default']
export const ProseBadge: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Badge.vue")['default']
export const ProseBlockquoteDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Blockquote.d.vue")['default']
export const ProseBlockquote: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Blockquote.vue")['default']
export const ProseCalloutDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Callout.d.vue")['default']
export const ProseCallout: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Callout.vue")['default']
export const ProseCardDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Card.d.vue")['default']
export const ProseCard: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Card.vue")['default']
export const ProseCardGroupDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/CardGroup.d.vue")['default']
export const ProseCardGroup: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/CardGroup.vue")['default']
export const ProseCodeDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Code.d.vue")['default']
export const ProseCode: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Code.vue")['default']
export const ProseCodeCollapseDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/CodeCollapse.d.vue")['default']
export const ProseCodeCollapse: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/CodeCollapse.vue")['default']
export const ProseCodeGroupDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/CodeGroup.d.vue")['default']
export const ProseCodeGroup: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/CodeGroup.vue")['default']
export const ProseCodeIconDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/CodeIcon.d.vue")['default']
export const ProseCodeIcon: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/CodeIcon.vue")['default']
export const ProseCodePreviewDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/CodePreview.d.vue")['default']
export const ProseCodePreview: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/CodePreview.vue")['default']
export const ProseCollapsibleDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Collapsible.d.vue")['default']
export const ProseCollapsible: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Collapsible.vue")['default']
export const ProseEmDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Em.d.vue")['default']
export const ProseEm: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Em.vue")['default']
export const ProseFieldDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Field.d.vue")['default']
export const ProseField: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Field.vue")['default']
export const ProseFieldGroupDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/FieldGroup.d.vue")['default']
export const ProseFieldGroup: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/FieldGroup.vue")['default']
export const ProseH1DVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/H1.d.vue")['default']
export const ProseH1: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/H1.vue")['default']
export const ProseH2DVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/H2.d.vue")['default']
export const ProseH2: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/H2.vue")['default']
export const ProseH3DVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/H3.d.vue")['default']
export const ProseH3: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/H3.vue")['default']
export const ProseH4DVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/H4.d.vue")['default']
export const ProseH4: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/H4.vue")['default']
export const ProseH5DVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/H5.d.vue")['default']
export const ProseH5: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/H5.vue")['default']
export const ProseH6DVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/H6.d.vue")['default']
export const ProseH6: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/H6.vue")['default']
export const ProseHrDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Hr.d.vue")['default']
export const ProseHr: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Hr.vue")['default']
export const ProseImgDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Img.d.vue")['default']
export const ProseImg: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Img.vue")['default']
export const ProseKbdDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Kbd.d.vue")['default']
export const ProseKbd: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Kbd.vue")['default']
export const ProseLiDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Li.d.vue")['default']
export const ProseLi: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Li.vue")['default']
export const ProseOlDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Ol.d.vue")['default']
export const ProseOl: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Ol.vue")['default']
export const ProsePDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/P.d.vue")['default']
export const ProseP: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/P.vue")['default']
export const ProsePreDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Pre.d.vue")['default']
export const ProsePre: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Pre.vue")['default']
export const ProseScriptDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Script.d.vue")['default']
export const ProseScript: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Script.vue")['default']
export const ProseStepsDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Steps.d.vue")['default']
export const ProseSteps: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Steps.vue")['default']
export const ProseStrongDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Strong.d.vue")['default']
export const ProseStrong: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Strong.vue")['default']
export const ProseTableDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Table.d.vue")['default']
export const ProseTable: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Table.vue")['default']
export const ProseTabsDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Tabs.d.vue")['default']
export const ProseTabs: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Tabs.vue")['default']
export const ProseTabsItemDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/TabsItem.d.vue")['default']
export const ProseTabsItem: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/TabsItem.vue")['default']
export const ProseTbodyDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Tbody.d.vue")['default']
export const ProseTbody: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Tbody.vue")['default']
export const ProseTdDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Td.d.vue")['default']
export const ProseTd: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Td.vue")['default']
export const ProseThDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Th.d.vue")['default']
export const ProseTh: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Th.vue")['default']
export const ProseTheadDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Thead.d.vue")['default']
export const ProseThead: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Thead.vue")['default']
export const ProseTrDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Tr.d.vue")['default']
export const ProseTr: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Tr.vue")['default']
export const ProseUlDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Ul.d.vue")['default']
export const ProseUl: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Ul.vue")['default']
export const ProseCautionDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/callout/Caution.d.vue")['default']
export const ProseCaution: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/callout/Caution.vue")['default']
export const ProseNoteDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/callout/Note.d.vue")['default']
export const ProseNote: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/callout/Note.vue")['default']
export const ProseTipDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/callout/Tip.d.vue")['default']
export const ProseTip: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/callout/Tip.vue")['default']
export const ProseWarningDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/callout/Warning.d.vue")['default']
export const ProseWarning: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/callout/Warning.vue")['default']
export const B24ColorModeAvatarDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/color-mode/ColorModeAvatar.d.vue")['default']
export const B24ColorModeAvatar: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/color-mode/ColorModeAvatar.vue")['default']
export const B24ColorModeButtonDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/color-mode/ColorModeButton.d.vue")['default']
export const B24ColorModeButton: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/color-mode/ColorModeButton.vue")['default']
export const B24ColorModeImageDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/color-mode/ColorModeImage.d.vue")['default']
export const B24ColorModeImage: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/color-mode/ColorModeImage.vue")['default']
export const B24ColorModeSelectDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/color-mode/ColorModeSelect.d.vue")['default']
export const B24ColorModeSelect: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/color-mode/ColorModeSelect.vue")['default']
export const B24ColorModeSwitchDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/color-mode/ColorModeSwitch.d.vue")['default']
export const B24ColorModeSwitch: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/color-mode/ColorModeSwitch.vue")['default']
export const B24AccordionDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Accordion.d.vue")['default']
export const B24Accordion: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Accordion.vue")['default']
export const B24AdviceDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Advice.d.vue")['default']
export const B24Advice: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Advice.vue")['default']
export const B24AlertDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Alert.d.vue")['default']
export const B24Alert: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Alert.vue")['default']
export const B24AppDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/App.d.vue")['default']
export const B24App: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/App.vue")['default']
export const B24AvatarDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Avatar.d.vue")['default']
export const B24Avatar: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Avatar.vue")['default']
export const B24AvatarGroupDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/AvatarGroup.d.vue")['default']
export const B24AvatarGroup: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/AvatarGroup.vue")['default']
export const B24BadgeDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Badge.d.vue")['default']
export const B24Badge: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Badge.vue")['default']
export const B24BannerDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Banner.d.vue")['default']
export const B24Banner: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Banner.vue")['default']
export const B24BreadcrumbDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Breadcrumb.d.vue")['default']
export const B24Breadcrumb: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Breadcrumb.vue")['default']
export const B24ButtonDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Button.d.vue")['default']
export const B24Button: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Button.vue")['default']
export const B24CalendarDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Calendar.d.vue")['default']
export const B24Calendar: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Calendar.vue")['default']
export const B24CardDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Card.d.vue")['default']
export const B24Card: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Card.vue")['default']
export const B24CheckboxDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Checkbox.d.vue")['default']
export const B24Checkbox: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Checkbox.vue")['default']
export const B24CheckboxGroupDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/CheckboxGroup.d.vue")['default']
export const B24CheckboxGroup: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/CheckboxGroup.vue")['default']
export const B24ChipDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Chip.d.vue")['default']
export const B24Chip: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Chip.vue")['default']
export const B24CollapsibleDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Collapsible.d.vue")['default']
export const B24Collapsible: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Collapsible.vue")['default']
export const B24ColorPickerDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/ColorPicker.d.vue")['default']
export const B24ColorPicker: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/ColorPicker.vue")['default']
export const B24CommandPaletteDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/CommandPalette.d.vue")['default']
export const B24CommandPalette: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/CommandPalette.vue")['default']
export const B24ContainerDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Container.d.vue")['default']
export const B24Container: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Container.vue")['default']
export const B24ContextMenuDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/ContextMenu.d.vue")['default']
export const B24ContextMenu: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/ContextMenu.vue")['default']
export const B24ContextMenuContentDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/ContextMenuContent.d.vue")['default']
export const B24ContextMenuContent: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/ContextMenuContent.vue")['default']
export const B24CountdownDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Countdown.d.vue")['default']
export const B24Countdown: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Countdown.vue")['default']
export const B24DashboardGroupDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/DashboardGroup.d.vue")['default']
export const B24DashboardGroup: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/DashboardGroup.vue")['default']
export const B24DashboardSearchDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/DashboardSearch.d.vue")['default']
export const B24DashboardSearch: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/DashboardSearch.vue")['default']
export const B24DashboardSearchButtonDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/DashboardSearchButton.d.vue")['default']
export const B24DashboardSearchButton: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/DashboardSearchButton.vue")['default']
export const B24DescriptionListDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/DescriptionList.d.vue")['default']
export const B24DescriptionList: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/DescriptionList.vue")['default']
export const B24DropdownMenuDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/DropdownMenu.d.vue")['default']
export const B24DropdownMenu: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/DropdownMenu.vue")['default']
export const B24DropdownMenuContentDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/DropdownMenuContent.d.vue")['default']
export const B24DropdownMenuContent: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/DropdownMenuContent.vue")['default']
export const B24EmptyDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Empty.d.vue")['default']
export const B24Empty: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Empty.vue")['default']
export const B24ErrorDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Error.d.vue")['default']
export const B24Error: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Error.vue")['default']
export const B24FieldGroupDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/FieldGroup.d.vue")['default']
export const B24FieldGroup: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/FieldGroup.vue")['default']
export const B24FileUploadDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/FileUpload.d.vue")['default']
export const B24FileUpload: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/FileUpload.vue")['default']
export const B24FormDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Form.d.vue")['default']
export const B24Form: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Form.vue")['default']
export const B24FormFieldDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/FormField.d.vue")['default']
export const B24FormField: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/FormField.vue")['default']
export const B24InputDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Input.d.vue")['default']
export const B24Input: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Input.vue")['default']
export const B24InputMenuDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/InputMenu.d.vue")['default']
export const B24InputMenu: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/InputMenu.vue")['default']
export const B24InputNumberDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/InputNumber.d.vue")['default']
export const B24InputNumber: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/InputNumber.vue")['default']
export const B24InputTagsDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/InputTags.d.vue")['default']
export const B24InputTags: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/InputTags.vue")['default']
export const B24KbdDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Kbd.d.vue")['default']
export const B24Kbd: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Kbd.vue")['default']
export const B24LinkDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Link.d.vue")['default']
export const B24Link: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Link.vue")['default']
export const B24LinkBaseDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/LinkBase.d.vue")['default']
export const B24LinkBase: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/LinkBase.vue")['default']
export const B24ModalDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Modal.d.vue")['default']
export const B24Modal: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Modal.vue")['default']
export const B24ModalDialogCloseDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/ModalDialogClose.d.vue")['default']
export const B24ModalDialogClose: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/ModalDialogClose.vue")['default']
export const B24NavbarDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Navbar.d.vue")['default']
export const B24Navbar: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Navbar.vue")['default']
export const B24NavbarDividerDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/NavbarDivider.d.vue")['default']
export const B24NavbarDivider: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/NavbarDivider.vue")['default']
export const B24NavbarSectionDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/NavbarSection.d.vue")['default']
export const B24NavbarSection: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/NavbarSection.vue")['default']
export const B24NavbarSpacerDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/NavbarSpacer.d.vue")['default']
export const B24NavbarSpacer: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/NavbarSpacer.vue")['default']
export const B24NavigationMenuDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/NavigationMenu.d.vue")['default']
export const B24NavigationMenu: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/NavigationMenu.vue")['default']
export const B24OverlayProviderDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/OverlayProvider.d.vue")['default']
export const B24OverlayProvider: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/OverlayProvider.vue")['default']
export const B24PageCardDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/PageCard.d.vue")['default']
export const B24PageCard: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/PageCard.vue")['default']
export const B24PageColumnsDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/PageColumns.d.vue")['default']
export const B24PageColumns: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/PageColumns.vue")['default']
export const B24PageGridDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/PageGrid.d.vue")['default']
export const B24PageGrid: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/PageGrid.vue")['default']
export const B24PageLinksDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/PageLinks.d.vue")['default']
export const B24PageLinks: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/PageLinks.vue")['default']
export const B24PageListDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/PageList.d.vue")['default']
export const B24PageList: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/PageList.vue")['default']
export const B24PaginationDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Pagination.d.vue")['default']
export const B24Pagination: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Pagination.vue")['default']
export const B24PinInputDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/PinInput.d.vue")['default']
export const B24PinInput: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/PinInput.vue")['default']
export const B24PopoverDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Popover.d.vue")['default']
export const B24Popover: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Popover.vue")['default']
export const B24ProgressDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Progress.d.vue")['default']
export const B24Progress: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Progress.vue")['default']
export const B24RadioGroupDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/RadioGroup.d.vue")['default']
export const B24RadioGroup: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/RadioGroup.vue")['default']
export const B24RangeDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Range.d.vue")['default']
export const B24Range: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Range.vue")['default']
export const B24SelectDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Select.d.vue")['default']
export const B24Select: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Select.vue")['default']
export const B24SelectMenuDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/SelectMenu.d.vue")['default']
export const B24SelectMenu: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/SelectMenu.vue")['default']
export const B24SeparatorDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Separator.d.vue")['default']
export const B24Separator: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Separator.vue")['default']
export const B24SidebarDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Sidebar.d.vue")['default']
export const B24Sidebar: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Sidebar.vue")['default']
export const B24SidebarBodyDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/SidebarBody.d.vue")['default']
export const B24SidebarBody: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/SidebarBody.vue")['default']
export const B24SidebarFooterDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/SidebarFooter.d.vue")['default']
export const B24SidebarFooter: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/SidebarFooter.vue")['default']
export const B24SidebarHeaderDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/SidebarHeader.d.vue")['default']
export const B24SidebarHeader: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/SidebarHeader.vue")['default']
export const B24SidebarHeadingDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/SidebarHeading.d.vue")['default']
export const B24SidebarHeading: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/SidebarHeading.vue")['default']
export const B24SidebarLayoutDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/SidebarLayout.d.vue")['default']
export const B24SidebarLayout: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/SidebarLayout.vue")['default']
export const B24SidebarSectionDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/SidebarSection.d.vue")['default']
export const B24SidebarSection: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/SidebarSection.vue")['default']
export const B24SidebarSpacerDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/SidebarSpacer.d.vue")['default']
export const B24SidebarSpacer: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/SidebarSpacer.vue")['default']
export const B24SkeletonDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Skeleton.d.vue")['default']
export const B24Skeleton: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Skeleton.vue")['default']
export const B24SlideoverDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Slideover.d.vue")['default']
export const B24Slideover: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Slideover.vue")['default']
export const B24StepperDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Stepper.d.vue")['default']
export const B24Stepper: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Stepper.vue")['default']
export const B24SwitchDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Switch.d.vue")['default']
export const B24Switch: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Switch.vue")['default']
export const B24TableDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Table.d.vue")['default']
export const B24Table: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Table.vue")['default']
export const B24TableWrapperDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/TableWrapper.d.vue")['default']
export const B24TableWrapper: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/TableWrapper.vue")['default']
export const B24TabsDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Tabs.d.vue")['default']
export const B24Tabs: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Tabs.vue")['default']
export const B24TextareaDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Textarea.d.vue")['default']
export const B24Textarea: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Textarea.vue")['default']
export const B24TimelineDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Timeline.d.vue")['default']
export const B24Timeline: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Timeline.vue")['default']
export const B24ToastDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Toast.d.vue")['default']
export const B24Toast: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Toast.vue")['default']
export const B24ToasterDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Toaster.d.vue")['default']
export const B24Toaster: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Toaster.vue")['default']
export const B24TooltipDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Tooltip.d.vue")['default']
export const B24Tooltip: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Tooltip.vue")['default']
export const B24UserDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/User.d.vue")['default']
export const B24User: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/User.vue")['default']
export const B24LocaleSelectDVue: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/locale/LocaleSelect.d.vue")['default']
export const B24LocaleSelect: typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/locale/LocaleSelect.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtTime: typeof import("../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyCompanyList: LazyComponent<typeof import("../app/components/CompanyList.vue")['default']>
export const LazyTicketTable: LazyComponent<typeof import("../app/components/TicketTable.vue")['default']>
export const LazyProseADVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/A.d.vue")['default']>
export const LazyProseA: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/A.vue")['default']>
export const LazyProseAccordionDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Accordion.d.vue")['default']>
export const LazyProseAccordion: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Accordion.vue")['default']>
export const LazyProseAccordionItemDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/AccordionItem.d.vue")['default']>
export const LazyProseAccordionItem: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/AccordionItem.vue")['default']>
export const LazyProseBadgeDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Badge.d.vue")['default']>
export const LazyProseBadge: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Badge.vue")['default']>
export const LazyProseBlockquoteDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Blockquote.d.vue")['default']>
export const LazyProseBlockquote: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Blockquote.vue")['default']>
export const LazyProseCalloutDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Callout.d.vue")['default']>
export const LazyProseCallout: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Callout.vue")['default']>
export const LazyProseCardDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Card.d.vue")['default']>
export const LazyProseCard: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Card.vue")['default']>
export const LazyProseCardGroupDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/CardGroup.d.vue")['default']>
export const LazyProseCardGroup: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/CardGroup.vue")['default']>
export const LazyProseCodeDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Code.d.vue")['default']>
export const LazyProseCode: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Code.vue")['default']>
export const LazyProseCodeCollapseDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/CodeCollapse.d.vue")['default']>
export const LazyProseCodeCollapse: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/CodeCollapse.vue")['default']>
export const LazyProseCodeGroupDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/CodeGroup.d.vue")['default']>
export const LazyProseCodeGroup: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/CodeGroup.vue")['default']>
export const LazyProseCodeIconDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/CodeIcon.d.vue")['default']>
export const LazyProseCodeIcon: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/CodeIcon.vue")['default']>
export const LazyProseCodePreviewDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/CodePreview.d.vue")['default']>
export const LazyProseCodePreview: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/CodePreview.vue")['default']>
export const LazyProseCollapsibleDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Collapsible.d.vue")['default']>
export const LazyProseCollapsible: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Collapsible.vue")['default']>
export const LazyProseEmDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Em.d.vue")['default']>
export const LazyProseEm: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Em.vue")['default']>
export const LazyProseFieldDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Field.d.vue")['default']>
export const LazyProseField: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Field.vue")['default']>
export const LazyProseFieldGroupDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/FieldGroup.d.vue")['default']>
export const LazyProseFieldGroup: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/FieldGroup.vue")['default']>
export const LazyProseH1DVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/H1.d.vue")['default']>
export const LazyProseH1: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/H1.vue")['default']>
export const LazyProseH2DVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/H2.d.vue")['default']>
export const LazyProseH2: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/H2.vue")['default']>
export const LazyProseH3DVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/H3.d.vue")['default']>
export const LazyProseH3: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/H3.vue")['default']>
export const LazyProseH4DVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/H4.d.vue")['default']>
export const LazyProseH4: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/H4.vue")['default']>
export const LazyProseH5DVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/H5.d.vue")['default']>
export const LazyProseH5: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/H5.vue")['default']>
export const LazyProseH6DVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/H6.d.vue")['default']>
export const LazyProseH6: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/H6.vue")['default']>
export const LazyProseHrDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Hr.d.vue")['default']>
export const LazyProseHr: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Hr.vue")['default']>
export const LazyProseImgDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Img.d.vue")['default']>
export const LazyProseImg: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Img.vue")['default']>
export const LazyProseKbdDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Kbd.d.vue")['default']>
export const LazyProseKbd: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Kbd.vue")['default']>
export const LazyProseLiDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Li.d.vue")['default']>
export const LazyProseLi: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Li.vue")['default']>
export const LazyProseOlDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Ol.d.vue")['default']>
export const LazyProseOl: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Ol.vue")['default']>
export const LazyProsePDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/P.d.vue")['default']>
export const LazyProseP: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/P.vue")['default']>
export const LazyProsePreDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Pre.d.vue")['default']>
export const LazyProsePre: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Pre.vue")['default']>
export const LazyProseScriptDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Script.d.vue")['default']>
export const LazyProseScript: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Script.vue")['default']>
export const LazyProseStepsDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Steps.d.vue")['default']>
export const LazyProseSteps: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Steps.vue")['default']>
export const LazyProseStrongDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Strong.d.vue")['default']>
export const LazyProseStrong: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Strong.vue")['default']>
export const LazyProseTableDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Table.d.vue")['default']>
export const LazyProseTable: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Table.vue")['default']>
export const LazyProseTabsDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Tabs.d.vue")['default']>
export const LazyProseTabs: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Tabs.vue")['default']>
export const LazyProseTabsItemDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/TabsItem.d.vue")['default']>
export const LazyProseTabsItem: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/TabsItem.vue")['default']>
export const LazyProseTbodyDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Tbody.d.vue")['default']>
export const LazyProseTbody: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Tbody.vue")['default']>
export const LazyProseTdDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Td.d.vue")['default']>
export const LazyProseTd: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Td.vue")['default']>
export const LazyProseThDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Th.d.vue")['default']>
export const LazyProseTh: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Th.vue")['default']>
export const LazyProseTheadDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Thead.d.vue")['default']>
export const LazyProseThead: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Thead.vue")['default']>
export const LazyProseTrDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Tr.d.vue")['default']>
export const LazyProseTr: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Tr.vue")['default']>
export const LazyProseUlDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Ul.d.vue")['default']>
export const LazyProseUl: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/Ul.vue")['default']>
export const LazyProseCautionDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/callout/Caution.d.vue")['default']>
export const LazyProseCaution: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/callout/Caution.vue")['default']>
export const LazyProseNoteDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/callout/Note.d.vue")['default']>
export const LazyProseNote: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/callout/Note.vue")['default']>
export const LazyProseTipDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/callout/Tip.d.vue")['default']>
export const LazyProseTip: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/callout/Tip.vue")['default']>
export const LazyProseWarningDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/callout/Warning.d.vue")['default']>
export const LazyProseWarning: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/prose/callout/Warning.vue")['default']>
export const LazyB24ColorModeAvatarDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/color-mode/ColorModeAvatar.d.vue")['default']>
export const LazyB24ColorModeAvatar: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/color-mode/ColorModeAvatar.vue")['default']>
export const LazyB24ColorModeButtonDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/color-mode/ColorModeButton.d.vue")['default']>
export const LazyB24ColorModeButton: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/color-mode/ColorModeButton.vue")['default']>
export const LazyB24ColorModeImageDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/color-mode/ColorModeImage.d.vue")['default']>
export const LazyB24ColorModeImage: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/color-mode/ColorModeImage.vue")['default']>
export const LazyB24ColorModeSelectDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/color-mode/ColorModeSelect.d.vue")['default']>
export const LazyB24ColorModeSelect: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/color-mode/ColorModeSelect.vue")['default']>
export const LazyB24ColorModeSwitchDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/color-mode/ColorModeSwitch.d.vue")['default']>
export const LazyB24ColorModeSwitch: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/color-mode/ColorModeSwitch.vue")['default']>
export const LazyB24AccordionDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Accordion.d.vue")['default']>
export const LazyB24Accordion: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Accordion.vue")['default']>
export const LazyB24AdviceDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Advice.d.vue")['default']>
export const LazyB24Advice: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Advice.vue")['default']>
export const LazyB24AlertDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Alert.d.vue")['default']>
export const LazyB24Alert: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Alert.vue")['default']>
export const LazyB24AppDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/App.d.vue")['default']>
export const LazyB24App: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/App.vue")['default']>
export const LazyB24AvatarDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Avatar.d.vue")['default']>
export const LazyB24Avatar: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Avatar.vue")['default']>
export const LazyB24AvatarGroupDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/AvatarGroup.d.vue")['default']>
export const LazyB24AvatarGroup: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/AvatarGroup.vue")['default']>
export const LazyB24BadgeDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Badge.d.vue")['default']>
export const LazyB24Badge: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Badge.vue")['default']>
export const LazyB24BannerDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Banner.d.vue")['default']>
export const LazyB24Banner: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Banner.vue")['default']>
export const LazyB24BreadcrumbDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Breadcrumb.d.vue")['default']>
export const LazyB24Breadcrumb: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Breadcrumb.vue")['default']>
export const LazyB24ButtonDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Button.d.vue")['default']>
export const LazyB24Button: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Button.vue")['default']>
export const LazyB24CalendarDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Calendar.d.vue")['default']>
export const LazyB24Calendar: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Calendar.vue")['default']>
export const LazyB24CardDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Card.d.vue")['default']>
export const LazyB24Card: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Card.vue")['default']>
export const LazyB24CheckboxDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Checkbox.d.vue")['default']>
export const LazyB24Checkbox: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Checkbox.vue")['default']>
export const LazyB24CheckboxGroupDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/CheckboxGroup.d.vue")['default']>
export const LazyB24CheckboxGroup: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/CheckboxGroup.vue")['default']>
export const LazyB24ChipDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Chip.d.vue")['default']>
export const LazyB24Chip: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Chip.vue")['default']>
export const LazyB24CollapsibleDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Collapsible.d.vue")['default']>
export const LazyB24Collapsible: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Collapsible.vue")['default']>
export const LazyB24ColorPickerDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/ColorPicker.d.vue")['default']>
export const LazyB24ColorPicker: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/ColorPicker.vue")['default']>
export const LazyB24CommandPaletteDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/CommandPalette.d.vue")['default']>
export const LazyB24CommandPalette: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/CommandPalette.vue")['default']>
export const LazyB24ContainerDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Container.d.vue")['default']>
export const LazyB24Container: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Container.vue")['default']>
export const LazyB24ContextMenuDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/ContextMenu.d.vue")['default']>
export const LazyB24ContextMenu: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/ContextMenu.vue")['default']>
export const LazyB24ContextMenuContentDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/ContextMenuContent.d.vue")['default']>
export const LazyB24ContextMenuContent: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/ContextMenuContent.vue")['default']>
export const LazyB24CountdownDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Countdown.d.vue")['default']>
export const LazyB24Countdown: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Countdown.vue")['default']>
export const LazyB24DashboardGroupDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/DashboardGroup.d.vue")['default']>
export const LazyB24DashboardGroup: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/DashboardGroup.vue")['default']>
export const LazyB24DashboardSearchDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/DashboardSearch.d.vue")['default']>
export const LazyB24DashboardSearch: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/DashboardSearch.vue")['default']>
export const LazyB24DashboardSearchButtonDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/DashboardSearchButton.d.vue")['default']>
export const LazyB24DashboardSearchButton: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/DashboardSearchButton.vue")['default']>
export const LazyB24DescriptionListDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/DescriptionList.d.vue")['default']>
export const LazyB24DescriptionList: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/DescriptionList.vue")['default']>
export const LazyB24DropdownMenuDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/DropdownMenu.d.vue")['default']>
export const LazyB24DropdownMenu: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/DropdownMenu.vue")['default']>
export const LazyB24DropdownMenuContentDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/DropdownMenuContent.d.vue")['default']>
export const LazyB24DropdownMenuContent: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/DropdownMenuContent.vue")['default']>
export const LazyB24EmptyDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Empty.d.vue")['default']>
export const LazyB24Empty: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Empty.vue")['default']>
export const LazyB24ErrorDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Error.d.vue")['default']>
export const LazyB24Error: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Error.vue")['default']>
export const LazyB24FieldGroupDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/FieldGroup.d.vue")['default']>
export const LazyB24FieldGroup: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/FieldGroup.vue")['default']>
export const LazyB24FileUploadDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/FileUpload.d.vue")['default']>
export const LazyB24FileUpload: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/FileUpload.vue")['default']>
export const LazyB24FormDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Form.d.vue")['default']>
export const LazyB24Form: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Form.vue")['default']>
export const LazyB24FormFieldDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/FormField.d.vue")['default']>
export const LazyB24FormField: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/FormField.vue")['default']>
export const LazyB24InputDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Input.d.vue")['default']>
export const LazyB24Input: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Input.vue")['default']>
export const LazyB24InputMenuDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/InputMenu.d.vue")['default']>
export const LazyB24InputMenu: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/InputMenu.vue")['default']>
export const LazyB24InputNumberDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/InputNumber.d.vue")['default']>
export const LazyB24InputNumber: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/InputNumber.vue")['default']>
export const LazyB24InputTagsDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/InputTags.d.vue")['default']>
export const LazyB24InputTags: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/InputTags.vue")['default']>
export const LazyB24KbdDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Kbd.d.vue")['default']>
export const LazyB24Kbd: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Kbd.vue")['default']>
export const LazyB24LinkDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Link.d.vue")['default']>
export const LazyB24Link: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Link.vue")['default']>
export const LazyB24LinkBaseDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/LinkBase.d.vue")['default']>
export const LazyB24LinkBase: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/LinkBase.vue")['default']>
export const LazyB24ModalDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Modal.d.vue")['default']>
export const LazyB24Modal: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Modal.vue")['default']>
export const LazyB24ModalDialogCloseDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/ModalDialogClose.d.vue")['default']>
export const LazyB24ModalDialogClose: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/ModalDialogClose.vue")['default']>
export const LazyB24NavbarDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Navbar.d.vue")['default']>
export const LazyB24Navbar: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Navbar.vue")['default']>
export const LazyB24NavbarDividerDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/NavbarDivider.d.vue")['default']>
export const LazyB24NavbarDivider: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/NavbarDivider.vue")['default']>
export const LazyB24NavbarSectionDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/NavbarSection.d.vue")['default']>
export const LazyB24NavbarSection: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/NavbarSection.vue")['default']>
export const LazyB24NavbarSpacerDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/NavbarSpacer.d.vue")['default']>
export const LazyB24NavbarSpacer: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/NavbarSpacer.vue")['default']>
export const LazyB24NavigationMenuDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/NavigationMenu.d.vue")['default']>
export const LazyB24NavigationMenu: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/NavigationMenu.vue")['default']>
export const LazyB24OverlayProviderDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/OverlayProvider.d.vue")['default']>
export const LazyB24OverlayProvider: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/OverlayProvider.vue")['default']>
export const LazyB24PageCardDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/PageCard.d.vue")['default']>
export const LazyB24PageCard: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/PageCard.vue")['default']>
export const LazyB24PageColumnsDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/PageColumns.d.vue")['default']>
export const LazyB24PageColumns: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/PageColumns.vue")['default']>
export const LazyB24PageGridDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/PageGrid.d.vue")['default']>
export const LazyB24PageGrid: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/PageGrid.vue")['default']>
export const LazyB24PageLinksDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/PageLinks.d.vue")['default']>
export const LazyB24PageLinks: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/PageLinks.vue")['default']>
export const LazyB24PageListDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/PageList.d.vue")['default']>
export const LazyB24PageList: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/PageList.vue")['default']>
export const LazyB24PaginationDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Pagination.d.vue")['default']>
export const LazyB24Pagination: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Pagination.vue")['default']>
export const LazyB24PinInputDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/PinInput.d.vue")['default']>
export const LazyB24PinInput: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/PinInput.vue")['default']>
export const LazyB24PopoverDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Popover.d.vue")['default']>
export const LazyB24Popover: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Popover.vue")['default']>
export const LazyB24ProgressDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Progress.d.vue")['default']>
export const LazyB24Progress: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Progress.vue")['default']>
export const LazyB24RadioGroupDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/RadioGroup.d.vue")['default']>
export const LazyB24RadioGroup: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/RadioGroup.vue")['default']>
export const LazyB24RangeDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Range.d.vue")['default']>
export const LazyB24Range: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Range.vue")['default']>
export const LazyB24SelectDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Select.d.vue")['default']>
export const LazyB24Select: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Select.vue")['default']>
export const LazyB24SelectMenuDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/SelectMenu.d.vue")['default']>
export const LazyB24SelectMenu: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/SelectMenu.vue")['default']>
export const LazyB24SeparatorDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Separator.d.vue")['default']>
export const LazyB24Separator: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Separator.vue")['default']>
export const LazyB24SidebarDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Sidebar.d.vue")['default']>
export const LazyB24Sidebar: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Sidebar.vue")['default']>
export const LazyB24SidebarBodyDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/SidebarBody.d.vue")['default']>
export const LazyB24SidebarBody: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/SidebarBody.vue")['default']>
export const LazyB24SidebarFooterDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/SidebarFooter.d.vue")['default']>
export const LazyB24SidebarFooter: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/SidebarFooter.vue")['default']>
export const LazyB24SidebarHeaderDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/SidebarHeader.d.vue")['default']>
export const LazyB24SidebarHeader: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/SidebarHeader.vue")['default']>
export const LazyB24SidebarHeadingDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/SidebarHeading.d.vue")['default']>
export const LazyB24SidebarHeading: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/SidebarHeading.vue")['default']>
export const LazyB24SidebarLayoutDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/SidebarLayout.d.vue")['default']>
export const LazyB24SidebarLayout: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/SidebarLayout.vue")['default']>
export const LazyB24SidebarSectionDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/SidebarSection.d.vue")['default']>
export const LazyB24SidebarSection: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/SidebarSection.vue")['default']>
export const LazyB24SidebarSpacerDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/SidebarSpacer.d.vue")['default']>
export const LazyB24SidebarSpacer: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/SidebarSpacer.vue")['default']>
export const LazyB24SkeletonDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Skeleton.d.vue")['default']>
export const LazyB24Skeleton: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Skeleton.vue")['default']>
export const LazyB24SlideoverDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Slideover.d.vue")['default']>
export const LazyB24Slideover: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Slideover.vue")['default']>
export const LazyB24StepperDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Stepper.d.vue")['default']>
export const LazyB24Stepper: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Stepper.vue")['default']>
export const LazyB24SwitchDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Switch.d.vue")['default']>
export const LazyB24Switch: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Switch.vue")['default']>
export const LazyB24TableDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Table.d.vue")['default']>
export const LazyB24Table: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Table.vue")['default']>
export const LazyB24TableWrapperDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/TableWrapper.d.vue")['default']>
export const LazyB24TableWrapper: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/TableWrapper.vue")['default']>
export const LazyB24TabsDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Tabs.d.vue")['default']>
export const LazyB24Tabs: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Tabs.vue")['default']>
export const LazyB24TextareaDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Textarea.d.vue")['default']>
export const LazyB24Textarea: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Textarea.vue")['default']>
export const LazyB24TimelineDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Timeline.d.vue")['default']>
export const LazyB24Timeline: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Timeline.vue")['default']>
export const LazyB24ToastDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Toast.d.vue")['default']>
export const LazyB24Toast: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Toast.vue")['default']>
export const LazyB24ToasterDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Toaster.d.vue")['default']>
export const LazyB24Toaster: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Toaster.vue")['default']>
export const LazyB24TooltipDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Tooltip.d.vue")['default']>
export const LazyB24Tooltip: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Tooltip.vue")['default']>
export const LazyB24UserDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/User.d.vue")['default']>
export const LazyB24User: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/User.vue")['default']>
export const LazyB24LocaleSelectDVue: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/locale/LocaleSelect.d.vue")['default']>
export const LazyB24LocaleSelect: LazyComponent<typeof import("../node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/locale/LocaleSelect.vue")['default']>
export const LazyNuxtWelcome: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']>
export const LazyNuxtLayout: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']>
export const LazyNuxtErrorBoundary: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']>
export const LazyClientOnly: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']>
export const LazyDevOnly: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']>
export const LazyServerPlaceholder: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyNuxtLink: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']>
export const LazyNuxtLoadingIndicator: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']>
export const LazyNuxtTime: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']>
export const LazyNuxtRouteAnnouncer: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']>
export const LazyNuxtImg: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']>
export const LazyNuxtPicture: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']>
export const LazyNuxtPage: LazyComponent<typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']>
export const LazyNoScript: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']>
export const LazyLink: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']>
export const LazyBase: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']>
export const LazyTitle: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']>
export const LazyMeta: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']>
export const LazyStyle: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']>
export const LazyHead: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']>
export const LazyHtml: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']>
export const LazyBody: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']>
export const LazyNuxtIsland: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']>

export const componentNames: string[]
